pipeline {
    agent { 
        node {
            label 'docker-agent-python'
            }
      }
    stages {
        /**stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh "sonar-scanner \
                        -Dsonar.projectKey=sonarqube-flask \
                        -Dsonar.sources=. \
                        -Dsonar.host.url= \
                        -Dsonar.login=
                }
            }
        }
        stage("Quality gate") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }*/
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                python3 -m unittest TestCalc.py
                
                '''
            }
        }
        /**stage('Docker Build') {
            steps {
                echo 'Building docker image from Dockerfile....'
                sh '''
                docker build --user='waseemabushagor' -t flask-app .
                '''

                echo 'Running Docker container......'
                sh '''
                docker run --user='waseemabushagor' -p 3000:3000 --name flask-app -d flask-app
                '''
            }
        }*/
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                // sudo nohup python3 app.py > log.txt 2>&1 &
                '''
            }
        }

    }
    '''post {
        success {
            discordSend description: "Jenkins Pipeline Build", footer: "Footer Text", link: env.BUILD_URL, result: currentBuild.currentResult, title: JOB_NAME, webhookURL: ""
        }
    }'''
}